name: Release Please

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        if: github.event_name != 'workflow_dispatch'
        id: release-please
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
